### ISSUE TITLE
Re-design ADCS PCB

### ISSUE THREAD

**Issue by ppapadeas** [librespacefoundation/upsat-adcs-hardware#1]
To fit new dimensions and cuts as attached

**Comment by ppapadeas** [comment]
PCB dimension spec can be found here:
https://owncloud.librespacefoundation.org/public.php?service=files&t=04128b0a20f9bfa0fad106c8898eb67f

**Comment by zisi** [comment]
Add MOSFET in GPS
Remove connection with COMMS, SU(SU_TH_GO/SU_TH_RET), EPS(RX/TX)
Remove IAC(DART), IAC_EN, USB_EN
Remove one SD card and add MOSFET for enabling SD card
Add connector for EPS (+5V, +3.3V, GND) or use existing
Re-design PCB for better cabling

**Comment by ykoveos** [comment]
We have RM3100 magnetometer, not RM3000. Small changes to pinout

**Comment by ppapadeas** [comment]
FPC connector placement specs can be found here:
https://owncloud.librespacefoundation.org/public.php?service=files&t=f833fb57909b6c4243d1718812d1eb7d
