### ISSUE TITLE
Which PCB programm did you use?

### ISSUE THREAD

**Issue by Missingo1996** [librespacefoundation/upsat-adcs-hardware#5]
When I try to open the schematics with Altium I do get an empty schematic.
When I try to open it with EAGLE I do get an Error.
How can I open the schematic?

**Comment by ppapadeas** [comment]
Hey @Missingo1996 , Try with KiCad :)

**Comment by Missingo1996** [comment]
@ppapadeas I tried it with KiCad too, it doenst work either.
Is it possible to provide a PDF Version of the schematic?
